syntax keyword typescriptGlobal containedin=typescriptIdentifierName describe it test
syntax keyword typescriptGlobal containedin=typescriptIdentifierName before after
syntax keyword typescriptGlobal containedin=typescriptIdentifierName beforeEach afterEach
syntax keyword typescriptGlobal containedin=typescriptIdentifierName beforeAll afterAll
syntax keyword typescriptGlobal containedin=typescriptIdentifierName expect assert
