syntax keyword javascriptBOMNavigatorProp contained battery buildID cookieEnabled
syntax keyword javascriptBOMNavigatorProp contained doNotTrack maxTouchPoints oscpu
syntax keyword javascriptBOMNavigatorProp contained productSub push vendor vendorSub
syntax keyword javascriptBOMNavigatorMethod contained addIdleObserver getDeviceStoragenextgroup=javascriptFuncArg
syntax keyword javascriptBOMNavigatorMethod contained getDeviceStorages getGamepadsnextgroup=javascriptFuncArg
syntax keyword javascriptBOMNavigatorMethod contained getUserMedia registerContentHandlernextgroup=javascriptFuncArg
syntax keyword javascriptBOMNavigatorMethod contained removeIdleObserver requestWakeLocknextgroup=javascriptFuncArg
syntax keyword javascriptBOMNavigatorMethod contained vibrate watch registerProtocolHandlernextgroup=javascriptFuncArg
