syntax keyword javascriptBOMLocationProp contained href protocol host hostname port
syntax keyword javascriptBOMLocationProp contained pathname search hash username password
syntax keyword javascriptBOMLocationProp contained origin
syntax keyword javascriptBOMLocationMethod contained assign reload replace toStringnextgroup=javascriptFuncArg
